#开发环境
#tomcat端口
server.servlet.content-path=/dsfa
server.port=8086
#使用CGLIB来实现AOP
spring.aop.proxy-target-class=true

#开启druid监控
spring.datasource.druid.monitor=true
spring.datasource.druid.loginUsername=_admin
spring.datasource.druid.loginPassword=dreamsoft


#调试模式 可实现热加载sql文件
spring.datasource.devMode = true
spring.datasource.druids[0].url=jdbc:mysql://localhost:3306/dsfa0611?useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true&useSSL=false&serverTimezone=UTC
spring.datasource.druids[0].username=root
spring.datasource.druids[0].password=123456
spring.datasource.druids[0].initialSize=3
spring.datasource.druids[0].minIdle=1
spring.datasource.druids[0].maxActive=5

#微服务名称
spring.application.name=dsfa
#微服务调度中心地址
eureka.client.service-url.defaultZone=http://10.128.2.103:7100/eureka/
#是否注册到服务器上
eureka.client.register-with-eureka=false
#可以访问其他微服务
eureka.client.fetch-registry=false

#上传文件存放目录 如果是负载均衡，建议设置成共享目录
dsf.file.upload-virtual-path=C:/Program Files/Apache Software Foundation/Tomcat 9.0/virtual/file
##视频、预览gif、封面输出路径
dsf.video.output=C:/Program Files/Apache Software Foundation/Tomcat 9.0/virtual/video
#ffmpeg程序目录
dsf.video.ffmpeg=C:/Users/D/ffmpeg


#定时任务通过数据库配置
spring.quartz.job-store-type=jdbc
#默认或是自己改名字都行
spring.quartz.properties.org.quartz.scheduler.instanceName=projectScheduler
#如果使用集群，instanceId必须唯一，设置成AUTO
spring.quartz.properties.org.quartz.scheduler.instanceId = AUTO

#线程池
spring.quartz.properties.org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
spring.quartz.properties.org.quartz.threadPool.threadCount=10
spring.quartz.properties.org.quartz.threadPool.threadPriority=5
spring.quartz.properties.org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread=true

#存储方式使用JobStoreTX，也就是数据库
spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate


#配置数据源
#数据库中quartz表的表名前缀
spring.quartz.properties.org.quartz.dataSource.quartzDs.driver = com.mysql.jdbc.Driver
spring.quartz.properties.org.quartz.dataSource.quartzDs.URL = mysql://localhost:3306/dsfa0611?useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true&useSSL=true
spring.quartz.properties.org.quartz.dataSource.quartzDs.user = root
spring.quartz.properties.org.quartz.dataSource.quartzDs.password = 123456
spring.quartz.properties.org.quartz.dataSource.quartzDs.maxConnections = 5

#是否使用集群（如果项目只部署到 一台服务器，就不用了）
spring.quartz.properties.org.quartz.jobStore.isClustered = true
spring.quartz.properties.org.quartz.jobStore.clusterCheckinInterval=20000
spring.quartz.properties.org.quartz.jobStore.tablePrefix = QRTZ_
spring.quartz.properties.org.quartz.jobStore.dataSource = quartzDs


# Redis数据库索引（默认为0）
#spring.redis.database=27
spring.redis.database=7
# Redis服务器地址
#spring.redis.host=10.128.2.104
#spring.redis.host=192.168.0.12
#spring.redis.host=192.168.0.34
spring.redis.host=localhost
# Redis服务器连接端口
#spring.redis.port=6413
spring.redis.port=6379
# Redis服务器连接密码（默认为空）
#spring.redis.password=DreamSoft_123
spring.redis.password=peppaappep
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.jedis.pool.max-idle=200
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.jedis.pool.max-wait=10
# 连接池中的最小空闲连接
spring.redis.jedis.pool.min-idle=10
# 连接超时时间（毫秒）

dsfa.debug=true