#发送通知公告角色id
notice.role.id=1db4c3af38424d9e87be04f4a2e4dc3e
#信息填报界面
filling.page=/situation/tbrw/notice/fill-task/skip_to_filling_page
#信息填报界面
audit.skip.page=/situation/audit/skip_to_audit_page
#信息审核界面
audit.page=/situation/auditManagement/approve/info/views/main.html
#校情上级审核角色id
audit.role.id=844856bd2c9f49c6b89061d7925de781
#省委党校treeInfoGlobalId
province.tree.info.global.id=1224c1afa99d4659b7980d408d18fcb7.ad59cb23baf24cf6ad550ca69364247d
#审核详情界面
audit_detail_page=/situation/auditManagement/approve/views/audit_detail.html
#校情本级校领导审核角色id
current.audit.role.id=0e9a943c5f2142719e7de9473e4d5202


